gem 'bundler'
gem 'bundler-unload'
gem 'guard'
gem 'guard-nanoc'
gem 'haml'
gem 'jsmin'
gem 'kramdown'
gem 'nanoc'
gem 'nanoc-embed'
gem 'redcarpet'
gem 'rubygems-bundler'
gem 'rvm'
gem 's3sync', '~> 2.0.2'
gem 'sass'
gem 'table_print'
